INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'doctrine_migration_versions', 'doctrine_migration_versions', 2, 'CREATE TABLE doctrine_migration_versions (version VARCHAR(191) NOT NULL, executed_at DATETIME DEFAULT NULL, execution_time INTEGER DEFAULT NULL, PRIMARY KEY(version))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_doctrine_migration_versions_1', 'doctrine_migration_versions', 3, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'sqlite_sequence', 'sqlite_sequence', 5, 'CREATE TABLE sqlite_sequence(name,seq)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'i23_paniers', 'i23_paniers', 4, 'CREATE TABLE i23_paniers (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_user INTEGER NOT NULL, produit_quantites CLOB NOT NULL --(DC2Type:array)
        , CONSTRAINT FK_625719616B3CA4B FOREIGN KEY (id_user) REFERENCES i23_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UNIQ_625719616B3CA4B', 'i23_paniers', 7, 'CREATE UNIQUE INDEX UNIQ_625719616B3CA4B ON i23_paniers (id_user)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'i23_produits', 'i23_produits', 8, 'CREATE TABLE i23_produits (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_panier INTEGER DEFAULT NULL, libelle VARCHAR(12) NOT NULL, prix DOUBLE PRECISION NOT NULL, enstock INTEGER NOT NULL, CONSTRAINT FK_4B08D5522FBB81F FOREIGN KEY (id_panier) REFERENCES i23_paniers (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'IDX_4B08D5522FBB81F', 'i23_produits', 9, 'CREATE INDEX IDX_4B08D5522FBB81F ON i23_produits (id_panier)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'i23_users', 'i23_users', 10, 'CREATE TABLE i23_users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, id_panier INTEGER DEFAULT NULL, login VARCHAR(180) NOT NULL, roles CLOB NOT NULL --(DC2Type:json)
        , password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, birth_day DATE DEFAULT NULL, CONSTRAINT FK_67D320482FBB81F FOREIGN KEY (id_panier) REFERENCES i23_paniers (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UNIQ_67D32048AA08CB10', 'i23_users', 11, 'CREATE UNIQUE INDEX UNIQ_67D32048AA08CB10 ON i23_users (login)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UNIQ_67D320485E237E06', 'i23_users', 12, 'CREATE UNIQUE INDEX UNIQ_67D320485E237E06 ON i23_users (name)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UNIQ_67D32048A9D1C132', 'i23_users', 13, 'CREATE UNIQUE INDEX UNIQ_67D32048A9D1C132 ON i23_users (first_name)');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'UNIQ_67D320482FBB81F', 'i23_users', 6, 'CREATE UNIQUE INDEX UNIQ_67D320482FBB81F ON i23_users (id_panier)');
